apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    database: security_rag
    user: postgres
    password: password
    host: postgres
    port: 5432
    sslmode: disable
    isDefault: true
    editable: true
